name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      env:
        CI: false

    - name: Run deploy script
      env:
        CI: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.name  ${{ github.actor }}
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git remote add origin https://github.com/caitlynrawlings/MacroCalculator.git
        npm run deploy -- -m "Deploy React app to GitHub Pages"
